### ISSUE TITLE
Font size / type options and Interface suggestions

### ISSUE THREAD

**Issue by XeroByt3** [SidneyNemzer/snippets#14]
I just discovered your extension and I really think this could be something I'd frequently used. It looks great 👍 

I just wanted to put in a few feature requests:

- Ability to change the font and size in the code editor. I find the current font is a bit too large for me.
- Also in the side nav bar I find the fonts are a bit larger than they need to be. It would be nice to be able to customise the font/size here as well
- Ability to minimize the side nav bar whilst editing code to give a bit more width to the code
- Word wrap in the code editor

Thank you!

**Comment by SidneyNemzer** [comment]
I'm glad you're getting some good use out of Snippets!

Regarding the font sizes, you can change the font size of the editor just like any other page in Chrome: Ctrl+scroll wheel. This will affect the entire Chrome devtools though. If that isn't ideal, let me know and I'll add font-size adjustment to the roadmap.

I plan to allow users to resize the sidebar, I just haven't gotten around to that yet ;)

Word wrap makes sense too, I'll get that in the next update! Probably this weekend.

**Comment by SidneyNemzer** [comment]
Word wrap is done, but I'll leave this open until we figure out what to do with the font size and I get the "collapse sidebar" button implemented.

**Comment by woutervandiggelen** [comment]
Being able to adjust the font-size would be awsome, at the moment it's a bit to big to my personal preference.

**Comment by SidneyNemzer** [comment]
Noted! I'll make the font size adjustable in a future update.

**Comment by SidneyNemzer** [comment]
I reduced the font size of the editor, although I still haven't added the config option yet. I think I'll be able to do that in the next update (although I'm not sure when that will be)

**Comment by SidneyNemzer** [comment]
This issue is almost a year old, does anyone still want adjustable font size? If so:

- Just for the editor (Ace), or the whole interface? (Including sidebar, settings, etc)
- Why not use Ctrl + Scroll to zoom the devtools?

Leave a comment if so and I'll reopen!
