### ISSUE TITLE
Save/Delete empty Snippet = error loop 

### ISSUE THREAD

**Issue by Pfennigbaum** [SidneyNemzer/snippets#19]
Whenever i try to delete an empty snippet, the extensions will move into an error loop.
It can only be revocered when i reload the whole gist.

Steps to reproduce:
1. Create Empty Snippet
2. Delete Empty Snippet

**Comment by SidneyNemzer** [comment]
So it turns out ASAP is not as soon as I would have liked. Please let me know if this bug is causing major issues for you, otherwise I'll address this when I have time to dedicate to Snippets.

**Comment by Pfennigbaum** [comment]
It's not casuing major issues for me as i am aware of it ;)
