### ISSUE TITLE
Add an options page

### ISSUE THREAD

**Issue by SidneyNemzer** [SidneyNemzer/snippets#7]
Currently, nothing is user-configurable

The following should be configurable:

* Tab size (for all snippets, not individual)
* Editor Theme
* Autocompletion on/off

**Comment by nionis** [comment]
Perhaps also include:

- auto run snippet

**Comment by SidneyNemzer** [comment]
@nionis I assume you mean an option that auto-runs the snippet you're working on after you save? That's a good idea!

Unfortunately I don't have much time to develop it right now :(

But (as you can see from the branches and issues) I have some major plans in the works :)

**Comment by nionis** [comment]
@SidneyNemzer What I mean is a way for the snippet to autorun once u load the page, so for example:
I can make a snippet hiding facebook posts mentioning the kardashians I wont have to manually run it every time I visit facebook

**Comment by SidneyNemzer** [comment]
@nionis Ah! Yes, I actually have that already planned, (I believe it's on the roadmap) although I'm not sure exactly when I'll get around to it

Good use case though
